Sprint 16
DmitriiMM/Tracker pull request #3
Opened 2023-05-13 12:11 UTC by DmitriiMM

2023-05-14 12:36 UTC, IBDesignable requested changes

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Models/CategoriesViewModel.swift
> +    private let categoriesViewController = CategoriesViewController()
Эта строчка во первых серьезная ошибка –  ViewModel не должна знать ничего про ViewController таким образом, это не укладывается в схему MVVM.

Во вторых, у тебя CategoriesViewController  создается на экране (NewTrackerViewController), а затем сам CategoriesViewController создает ViewModel – который уже создает еще раз CategoriesViewController. То есть одновременно  создано два контроллера 🤯

В третьих, тут это свойство вообще ни как не используется, по тому можно смело удалять.

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Models/CategoriesViewModel.swift
> +    }
convenience init() можно конечно оставить.

но можно лучше! обычно существует некоторая сущность с фабричным паттерном, которая собирает MVVM-модуль. То есть она создает (или хранит предсозданный) categoryStore, затем с ним создает ViewModel через второй иницализатор (`init(categoryStore:)`), затем создает контроллер с этой ViewModel. 

Такие фабрики часто называют ассамблеями Assembly. И их создают по одной на каждый такой модуль. 

В месте перехода ты обращаешься к такой фабрике, просишь создать модуль, если надо передаешь первоначальные настройки с предыдущего экрана, а как результат – получаешь не конкретный ViewController, а просто UIViewController.

например так:

```swift
func assemble(_ someConfiguration: SomeConfiguration) -> UIViewController {
  let dataStore = DataStore()
  let viewModel = ViewModel(dataStore: dataStore) 
  let viewController = SomeViewController(viewModel: viewModel)
  return viewController
}
```

конфигурации может не быть, если не нужно ничего передавать.

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +        case "updatedCategory":
при возможности лучше избегать ключей со строками и вот таким вот поиском в свитче не заниматься.

в качестве ключа, который всегда будет существовать и их ограниченное количество, лучше использовать кейсы Enum-ов&

Давай как раз на них здесь и перейдем

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +        case "updatedCategory":
Я вижу что такой поход используется прямо везде, и если у тебя получится – лучше от него отказаться и отрефакторить.

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
>      func onTransition<T>(value: T, for key: String) {
Этот дженерик не выглядит универсальным, особенно в паре со строковым ключом. 

Если идея была в том, чтобы написать универсальный протокол, то в Value лучше использовать свои конкретные типы. Не string и словарь: не string,  NewСategory(let name: String), не словарь, а EditedCategory( let initialCategory: String, let updatedName: String).

Тогда можно будет написать реализцию под каждый случай, и пользовать дженериками в полной мощи, и от ключей отказаться:
```swift
func onTransition<T>(value: T) where T == NewСategory {
 ... 
}
func onTransition<T>(value: T) where T == EditedCategory {
}
```

в данном случае, использование дженериков не верное :(

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/NewCategoryViewController.swift
> +                    }
лучше не делать в комплишенах эти операции, а делать синхронно вызовы delegateTransition?.onTransition, затем диссмисс

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/OnboardingViewController.swift
> +
Надо запомнить правило: вью контроллеры не надо хранить ссылками в других вью-контроллерах, а создавать их по мере необходимости, то есть при навигации.

Например, когда ты настраиваешь UIPageViewController - используешь setViewControllers -в этот момент создать первый, а когда будешь навигировать каруселью ко второму (через методы делегата), создавать второй, и так далее. 

Кроме того вместо того чтобы хранить их массивом здесь в pages, можно было бы описать используемые страницы через CaseIterable enum: OnboardingPages (first,second)


В целом здесь можно лучше сделать:

если присмотреться, страницы выглядят одинаково.
Вместо того чтобы настраивать каждый экран два раза, писать одинаковые констрейнты, создавать по лейбле для каждого –  можно было бы создать OnboardingPageViewController – описать на нем один раз верстку и настройку элементов. 

И иницализировать страницы пейджа данными (например кейсом енама), в зависимости уже от сценария подбирать изображение, текст. 

Так ты перестаешь повторяться, и выстраиваешь логику взаимодействия, моделируешь ее через сущности, а не через перечисление подряд много раз одного и того же. Онбординги вообще популярная штука в продуктах сейчас, и они далеко не всегда из одной странички состоят, и представь если тебе нужно 5 таких страниц сделать, до куда будет контроллер бухнуть от повторяющейся верстки?

Запоминаем еще правило: если ты что-то делаешь второй раз, пора задуматься, как это написать единожды.

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/OnboardingViewController.swift
> +
https://github.com/cjlarsen/Tutorials/tree/master/PageControllerTutorial - подсмотреть направление мыслей предлагаю тут, хотя код там страшненький

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +    private var viewModel: CategoriesViewModel!
будет круто, если добавишь инициализатор от ViewModel, чтобы вьюконтроллер сам ее не создавал

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +        present(alert, animated: true)
Почему бы опять не воспользоваться знаниями из MovieQuiz и не забрать от туда презентер (и немного доработать)

Вообще классное правило бы выработать: все чему научился в прошлый раз, попробовать применить в новом месте)

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Models/CategoriesViewModel.swift
> +import UIKit
Никакого UIKit-а в Model/ViewModel слое, надо избавиться

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
>          cell.textLabel?.font = UIFont.appFont(.regular, withSize: 17)
а почему шрифт каждый раз устанавливается? можно это сделать всего раз?

тоже самое и про фон

2023-05-14 12:36 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
>      var checkmarkedCell: IndexPath?
есть ощущение, что это логика ViewModel – выбранная ячейка, и тут схалявлено)

2023-05-16 20:25 UTC, DmitriiMM commented
@IBDesignable, я избавился от ""ScreenTransitionProtocol { func onTransition<T>(value: T, for key: String)..."" и добавил значительное количество делегатов под каждый вью контроллер. Ключи String это плохо, я это понимал и до проверки, но не думал что прям критично. Но один общий протокол для передачи любых данных между любыми вью контроллерами - это, на мой взгляд значительно лучше чем так как реализована связь в последнем коммите. Возможно я как то неверно написал метод onTransition. Дженерик тип был только для того чтобы в параметр передавать данные любого типа. Но как по мне, сейчас код выглядит менее опрятно с целой кучей разных протоколов и методов суть у которых одна - передать данные на один экран назад.

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +    init(viewModel: CategoriesViewModel, lastCategory: IndexPath?) {
Все еще считаю, что `lastCategory: IndexPath?` - это часть логики модуля, то есть значение можно получать из вью-модели.

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +        guard let checkmarkedCell = checkmarkedCell else { return }
checkmarkedCell - по названию прочитала и перепугалась что ты хранишь ссылки на ячейки, так не надо делать) а оказывается это название индекса – хорошо бы это отразить в названии 

Про нейминг надо больше почитать, чтобы прокачивать насмотренность пока нет рабочих проектов
https://habr.com/ru/companies/dododev/articles/714512/

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
>      }
в классике, этот метод тоже должен переехать во ViewModel.
то есть в методе  `tableView(_ tableView:, contextMenuConfigurationForRowAt:, point:) -> UIContextMenuConfiguration?`  нужно не deleteCategory вызывать, а ходить во ViewModel и передавать в нее indexPath.row. 

Дальше ViewModel узнает о категории для удаления, соберет AlertModel и например, в байдинговое свойство поместит `alertModel`. Которое уже ViewController отследит и покажет алерт с AlertPresenter`а.


---

я понимаю, почему это сложно увидеть. Но в жизни обычно так: у тебя пользователь делает какое-то действие с элементом (кнопка, ячейка), а тебе например нужно это действие отвалидировать, затрекать в системах аналитики, может быть сгонять за данными, логи собрать. В общем там прям пошуршать по разным сервисам приходится и ViewModel она как бы связующее звено, закрывает в себе все нужные связи с зависимостями, чтобы вью-слой про них ничего не знал.

Здесь тяжело это все прочувствовать с первого раза. Но это важно понять, и сделать по канону без ошибок

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +        else { return }
почему бы эту проверку не перенести во ViewModel?

Надо стремиться чтобы никакой валидации, условий-ветвлений с данными на вью слое не должно было быть

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +        if let heightConstraint = tableView.constraints.first(where: { $0.firstAttribute == .height && $0.relation == .equal && $0.secondItem == nil && $0.secondAttribute == .notAnAttribute }) {
у меня на экране строчка не помещается. 

А вообще, вместо того, чтобы делать поиск по констрентам, его можно сохранить в переменную класса. 
Для этого придется его создать вне группы, и активировать как единичное свойство (.isActive = true)
Обычно такой поиск никто не делает)

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/NewTrackerViewController.swift
> +            else { return }
Нужно стараться держать код в консистентном состоянии и не смешивать подходы/стили.
Посмотри, ты одну круглую скобку на новую строчку перенес, а другую оставил на той же строке

Это не последовательно, и потому код как будто бы в один пельмень слипается, разобрать тяжело)

```suggestion
            guard 
                let categoriesVC = SomeCoordinator.start(
                    with: SomeConfiguration(lastCategory: lastCategory)
                ) as? CategoriesViewController
            else { return }
```

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/PageViewController.swift
> +final class PageViewController: UIViewController {
какова красота :)

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/ScheduleViewController.swift
>      private let days = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"]
Для дней кстати, можно завести тоже enum - перечислить последовательность. Добавить вычислимых свойств для названий длинных и короотких. Подписать под протокол CaseIterable чтобы получать красиво весь список (allCases) 

Код сильно упростится местами и не будет так сильно зависеть от копипасты)

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Controllers/TrackerViewController.swift
> +        try! trackerCategoryStore.saveTracker(tracker: newTracker, to: titleNewCategory)
это что такое :) do-catch, try? хотя бы :)

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Supporting Files/Helpers/Coordinator.swift
> +struct SomeConfiguration {
ну какая же она some - вполне конкретная – TrackerCategory :) тоже и для SomeCoordinator. 

Я когда про асамблеи писала - приводила пример для краткости. Извини что не предупредила)

2023-05-17 19:05 UTC, IBDesignable commented on Tracker/Supporting Files/Helpers/Coordinator.swift
> +        let viewController = CategoriesViewController(viewModel: viewModel, lastCategory: configuration.lastCategory)
как уже выше писала, еще lastCategory должна уехать во ViewModel

2023-05-17 19:13 UTC, IBDesignable commented
> @IBDesignable, я избавился от ""ScreenTransitionProtocol { func onTransition(value: T, for key: String)..."" и добавил значительное количество делегатов под каждый вью контроллер. Ключи String это плохо, я это понимал и до проверки, но не думал что прям критично. Но один общий протокол для передачи любых данных между любыми вью контроллерами - это, на мой взгляд значительно лучше чем так как реализована связь в последнем коммите. Возможно я как то неверно написал метод onTransition. Дженерик тип был только для того чтобы в параметр передавать данные любого типа. Но как по мне, сейчас код выглядит менее опрятно с целой кучей разных протоколов и методов суть у которых одна - передать данные на один экран назад.

Слушай, на самом деле это очень классная идея написать один общий протокол, и в этом как раз не было проблемы. 
Там скорее очень плохо было понятно что ты вообще пытался решить. я не поняла без объяснения.

Дженерик там кажется серебренной пулей, но он там не работал так, как придуман в языке. С таким же успехом можно было поставить тип Any и кастить как тебе хочется. Решение бы тоже полагаю работало) 
Дженерики мы используем когда хотим реализовать некоторое поведение для определенного класса(категории/типа) элементов. Например, в задаче получения ответа от бекенда, дженерик функция супер работала, потому что мы хотели в конце получить объект с ограничением Decodable. И работало оно именно так: ты даешь тип, который удавлетворяет протоколу, компилятор во время компиляции понимает что это за тип и предлагает нам соответствующую реализацию функции.

В твоем же варианте никакого вычисления типа на этапе компиляции не происходило, все вычисления в рантайме: то есть ты гвозди забиваешь микроскопом :) 
То же самое и со строками: именно по этому с ними отказываются работать для такого класса задач. Высока вероятность опечатки/копипасты, нет проверки компилятором что то что ты делаешь – верная штука. 

Да и вообще, написать простой, понятный код (вот в лоб), нежели сложный и ветвлистый – куда хуже. Поэтому ничего плохо в протоколах нет. Да не привычно писать так много классов :) если у тебя каждый модуль одинаковый по структуре, скорее всего у тебя будет написан под него сниппет. Так что не переживай – стало лучше

2023-05-17 19:22 UTC, DmitriiMM commented on Tracker/Controllers/PageViewController.swift
> +final class PageViewController: UIViewController {
Здесь нэйминг? или еще что-то?))

2023-05-17 20:01 UTC, DmitriiMM commented
> > @IBDesignable, я избавился от ""ScreenTransitionProtocol { func onTransition(value: T, for key: String)..."" и добавил значительное количество делегатов под каждый вью контроллер. Ключи String это плохо, я это понимал и до проверки, но не думал что прям критично. Но один общий протокол для передачи любых данных между любыми вью контроллерами - это, на мой взгляд значительно лучше чем так как реализована связь в последнем коммите. Возможно я как то неверно написал метод onTransition. Дженерик тип был только для того чтобы в параметр передавать данные любого типа. Но как по мне, сейчас код выглядит менее опрятно с целой кучей разных протоколов и методов суть у которых одна - передать данные на один экран назад.
> 
> Слушай, на самом деле это очень классная идея написать один общий протокол, и в этом как раз не было проблемы. Там скорее было не понятно, что ты вообще пытался решить. Я не поняла без объяснения.
> 
> Дженерик там кажется серебренной пулей, но он там не работал так, как придуман в языке. С таким же успехом можно было поставить тип Any и кастить как тебе хочется. Решение бы тоже работало) Дженерики мы используем когда хотим реализовать некоторое поведение для определенного класса(категории/типа) элементов. Например, в задаче получения ответа от бекенда, дженерик функция супер работала, потому что мы хотели в конце получить объект с ограничением Decodable. И работало оно именно так: ты даешь тип, который удовлетворяет протоколу, компилятор во время компиляции понимает, что там за тип и предлагает нам соответствующую реализацию функции.
> 
> В твоем же варианте никакого вычисления типа на этапе компиляции не происходило, все вычисления в рантайме: то есть ты гвозди забиваешь микроскопом :) То же самое и со строками: именно по этому с ними отказываются работать для такого класса задач. Высока вероятность опечатки/копипасты, нет проверки компилятором что то что ты делаешь – верная штука.
> 
> Да и вообще, написать простой, понятный код (вот в лоб), нежели сложный и ветвлистый, – лучше, всегда сто процентно проканает на проверке. Поэтому ничего плохо в протоколах нет. Да не привычно писать так много классов :) если у тебя каждый модуль одинаковый по структуре, скорее всего у тебя будет написан под него сниппет. Так что не переживай – стало лучше
> 
> Тут я не хочу загасить желание писать сложный код и разбираться с новыми фишками языка – нет, конечно) пробуй и пытайся, но не забывай прикладывать поясняющие записки)

Для меня видимо представляется наоборот что есть сложный код а что простой понятный в лоб) Если бы мой ScreenTransitionProtocol был без дженерика и на Any, а для ключей был бы один большой Енам под все возможные ключи по всему приложению, то этот код не вызывал бы вопросов? то есть тогда можно его назвать простым удобным и тд или же подход с протоколами на каждый вьюконтроллер заработал бы больше очков простоты логичности и лаконичности? 
И еще вопрос про Координатор. Вот эту функцию ассамблею я правильно реализовал? Просто не уверен что правильно понял суть этой штуки.

2023-05-20 17:45 UTC, DmitriiMM commented on Tracker/Controllers/CategoriesViewController.swift
> +    init(viewModel: CategoriesViewModel, lastCategory: IndexPath?) {
@IBDesignable не могу логику понять. вьюмодель создается одновременно с вьюконтроллером. значит в ней не может храниться информация о том какая ячейка была нажата в прошлый раз. хранить нужный индекспас все равно придется во вьюконтроллере создания нового трекера NewTrackerViewController. тогда как уйти от архитектурной ошибки? нажимаю на ячейку, она отмечается, ее индекспас передается делегатом на NewTrackerViewController для сохранения. при создании CategoriesViewController передаю сохраненный индеспас и табличка со списком категорий рисуется сразу с галочкой в нужном месте. куда в эту цепочку положить вьюмодель я не понимаю

2023-05-22 08:37 UTC, IBDesignable commented on Tracker/Controllers/PageViewController.swift
> +final class PageViewController: UIViewController {
Здесь весь файл - молодец!

2023-05-22 09:13 UTC, DmitriiMM commented on Tracker/Controllers/PageViewController.swift
> +final class PageViewController: UIViewController {
я правда не понимаю. это же сарказм, "красота" и "молодец"? кроме неправильно названного класса в чем еще проблема?

2023-05-22 09:18 UTC, IBDesignable commented
> Для меня видимо представляется наоборот что есть сложный код а что простой понятный в лоб) Если бы мой ScreenTransitionProtocol был без дженерика и на Any, а для ключей был бы один большой Енам под все возможные ключи по всему приложению, то этот код не вызывал бы вопросов? то есть тогда можно его назвать простым удобным и тд или же подход с протоколами на каждый вьюконтроллер заработал бы больше очков простоты логичности и лаконичности?

Если бы ты заменил на Any и убрал строки: да стало бы лучше, так как не стал бы вводить в заблужение при использовании дженерик типа.
Все возможные ключи – просто про упоминание такой сущности представь большое приложение, например Вконтакте, вряд ли же там таким занимаются? 

Такое решение все равно было бы лучше предыдущего, но от всех проблем бы не избавилось: универсальным оно не будет, размер енама/перебора вариантов будет расти с каждым новым экраном. Другие экраны будут знать про эти оставшиеся ключи, хотя не должны. То есть про лаконичность здесь речи и не будет. 

Иными словами: будет лучше, но все еще плохо. 

Я думаю это понимание придет со временем, когда поработаешь с другими архитектурами или с большими проектами.

2023-05-22 09:19 UTC, IBDesignable reviewed
Все же не могу принять из-за избыточных и не к месту форсов.

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Supporting Files/Helpers/Coordinator.swift
>  }
> И еще вопрос про Координатор. Вот эту функцию ассамблею я правильно реализовал? Просто не уверен что правильно понял суть этой штуки.

То что ты сделал,
1) название координатора не очень удачно, все-таки есть имена которые общеприняты [для особых целей](https://www.hackingwithswift.com/articles/71/how-to-use-the-coordinator-pattern-in-ios-apps). Когда проверяющий разработчик откроет файл Coordinator, то будет ожидать там нечто похожее из статьи, а внутри статическая фабрика – лишнее разочарование :)
2) не забывай при изменении нейминга менять и название файла
3) сама реализация идеи – в целом окей, хотя я бы от статики отказалась: у класса нет никаких зависимостей, которые где-то бы пришлось дособирать. Поэтому в месте создания экрана вызвать `= CategoryCoordinator().assemble(with: categoryConfiguration)` – не зазорно), и лишнюю память статика занимать тогда не будет ([тема диспетчеризации](https://habr.com/ru/articles/673400/). Еще раз: идея выполнена хорошо, на данном этапе большего и не требовалось)

Поэтому извини, что не прокомментировала подробно в прошлый раз – засчитала как OK)

Если говорить о том, что я описывала, то должно было получиться так: класс `CategoriesAssembly`, с функцией `func assemble(with configuration:) -> UIViewController`.

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Domain/WeekDaysMarshalling.swift
> +                    }
колдунство) 

Не понятно на сколько правильно и какого вида сюда приходит строка. Может прийти вот что угодно и откуда угодно, что днями вовсе не являлось, и ты получишь на выходе список дней. Вообще в целом - минимизировать задачи, где приходится вот так перебирать строку. И пробовать приводить общение к таким данным как Weekday. Идея в том, чтобы максимально перенести валидацию данных на компилятор, и меньше создавать решений, где в рантайме можно получить из яблока грушу)

Если этот метод используется только для общения с БД: то можно попробовать там хранить список rawValue (от weekdays) 

Не обязательно править, но можно еще повертеть и придумать как избавиться от этого кода. Я вот не понимаю зачем "1", что он символизирует и почему строкой) одни вопросы)

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Domain/WeekDaysMarshalling.swift
> +    private let weekdays = Weekday.allCases
очень хорошо)

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Domain/TrackerCategoryStore.swift
> +        let updatedCategoryCD = try! fetchCategory(with: label)
пропустила в прошлый раз, никто ж не разрешал force делать – все еще против такого подхода. Тем более метод помечен throws, что вообще исключает необходимость делать try? или do-catch, то есть форс избыточен

Твоя задача максимально стараться, чтобы писать отказоустойчивый код: это полезный навык, думать как приложение себя ведет в экстремальных ситуациях, и добавляет очки Гриффиндор при проверке тестовых. Не пренебрегай пожалуйста этим правилом. 

Здесь  очень много строк где все может пойти не так: начиная от запроса, заканчивая попыткой сохранения результата. Если метод не должен быть throws, то стоит подумать какую ошибку вернуть и как ее обработать для пользователя: может ему надо показать просто ошибку или предложить повторить действие? Или программно откатить изменения. Работа с базами данных обычно требует всех этих действий. 

Сейчас "игрушечная" задача, где эти вопросы перед тобой авторы не поставили для упрощения и сокращения времени работы над спринтом. Потому что вопросы-то не тривиальные, требуют проработки от разработчика, "правильного" единственного решения не существует. Но на деле - это основная часть твоей ответственности, как разработчика. И на обнаружение, продумывание и поиска защитных решений и уходит большая часть времени работы над подобным классом задач. Поэтому считаю полезным тренироваться на безопасных задачах, где от твоей ошибки не зависит выручка компании и жизни людей)

Я не буду реджектить из-за этого всю работу, так как не считаю это частью спринта. Но очень надеюсь, что ты к этому вернешься.

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Controllers/PageViewController.swift
> +    case pageOne
Хорошо бы удостоить Pages отдельного файла)

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +           heightTableView = viewModel.categories!.count * 75 - 1
Опять форс операция. Нужно разыменовать. 

Хотя тут даже плохо не сама форс операция, а потребность вычислять высоту таблицы. Таблица - это scrollView и она сама умеет управлять размером своего контента. В нашем макете не вижу ни одной причины заниматься такими вычислениями. 
Я думаю стоит обсудить возникнувшую проблему и возможные другие решения с Наставником (так как это выглядит как консультация, которую в ревью проводить не могу)

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +            AlertPresenter().show(controller: self, model: self.viewModel.alertModel!)
аналогично, пренебрегаешь опционалом и делаешь форс:

`guard let self, let alertModel = self.viewModel.alertModel` - как будто бы вот так можно было решить.

Но! ты же байндишь, это значит что модель должна быть аргументом байндинга (который здесь займьючен _)

то есть если он опциональный надо было написать так:

```swift
viewModel.$alertModel.bind { [weak self] alertModel in
 guard let self, let alertModel else { return } 
AlertPresenter().show(controller: self, model: alertModel)
}```

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +                self.heightTableView = self.viewModel.categories!.count * 75 - 1
а здесь не только форсы повторяются, но еще и код дублируется

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
> +                self.tableViewHeightConstraint!.constant = CGFloat(self.heightTableView)
Один знак меняем, а уже к крашу не приведем
```suggestion
                self.tableViewHeightConstraint?.constant = CGFloat(self.heightTableView)
```

2023-05-22 09:19 UTC, IBDesignable commented on Tracker/Domain/TrackerCategoryStore.swift
> +        let updatedCategoryCD = try! fetchCategory(with: label)
переобуваюсь: давай поправим вместе с остальными форсами

2023-05-23 20:43 UTC, DmitriiMM commented
> Опять форс операция. Нужно разыменовать.
> 
> Хотя тут даже плохо не сама форс операция, а потребность вычислять высоту таблицы. Таблица - это scrollView и она сама умеет управлять размером своего контента. В нашем макете не вижу ни одной причины заниматься такими вычислениями. Я думаю стоит обсудить возникнувшую проблему и возможные другие решения с Наставником (так как это выглядит как консультация, которую в ревью проводить не могу)


Пожалуйста, можно чуть подробнее про автоматическое изменение высоты таблицы? Правильно понимаю что дело не в фиксированной высоте ячейки 75 зашитой в код? Никому не расскажу, что здесь случилась консультация)

2023-05-24 20:53 UTC, IBDesignable approved these changes

2023-05-24 20:53 UTC, IBDesignable commented on Tracker/Domain/TrackerRecordStore.swift
> +            guard let record = try? makeTrackerRecord(from: i) else { return [] }
ой, лучше бы я не видела нейминга И по Обжектс))

```swift
objects.compactMap { try? makeTrackerRecord(from: $0) }
```
compactMap - все опциональные результаты схлопывает (пропускает), и итоге получает коллекцию неопциональных значений.

результат уже можно положить в recordsSet прям пачкой.

нейминг c `i` - лучше оставить для математических задач, таких в ios практике у тебя будет не много, в любых других ситуаций лучше слово в единственном числе использовать `for object in objects`.

Здесь еще одна проблема, не знаю на сколько тебе ОК с ней:  если во всем масиве, только первая запись будет давать нил при выполнении makeTrackerRecord, то другие обрабатываться не будут (будет вызван return []), ты точно такое поведение планировал? выглядит как сайдэффект, которого стоило избегать

2023-05-24 20:53 UTC, IBDesignable commented on Tracker/Supporting Files/SceneDelegate.swift
> +        }
ну и на финальную, если еще не упоминала, `UserDefaults.standard.bool(forKey: "hasShownOnboarding")` - стоит поместить работу с этим свойством в отдельный сервис (дата сторадж), как мы делали в прошлом модуле с токеном. 

Таскать с собой строковый ключ, и юзер дефолтс, да в sceneDelegate  - грязновато.

2023-05-24 20:58 UTC, IBDesignable commented
> Пожалуйста, можно чуть подробнее про автоматическое изменение высоты таблицы? Правильно понимаю что дело не в фиксированной высоте ячейки 75 зашитой в код? Никому не расскажу, что здесь случилась консультация)

Позволю показать тебе [стековерфлоу](https://stackoverflow.com/a/18746930/10764177), там прям подробно тоже самое (может чуть корректнее описано) 

Залог успеха: констрейнты в ячейке, и свойство `tableView.rowHeight = UITableViewAutomaticDimension` 

PS: Консультации ревьюверам не оплачиваются отдельно, Дмитрий, поэтому нам и запрещают их делать – чтобы мы успевали обрабатывать все работы студентов! извини, но твое ревью уже вышло за все выданное мне время на тебя 😀 пожалуйста, домучай Наставников на этот счет)) я уверена они справятся с таким вопросом даже лучше меня!))

2023-05-26 08:02 UTC, merged